# Generated by Django 6.0.3 on 2026-03-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomspecialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Traiteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=20)),
                ('est_actif', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('datedecreation', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=20)),
                ('image', models.URLField(blank=True, null=True)),
                ('specialite', models.ManyToManyField(to='services.specialites')),
            ],
        ),
    ]
