# Generated by Django 4.2.23 on 2026-04-03 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomspecialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Traiteurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=20)),
                ('est_actif', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('datedecreation', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='traiteurs/')),
                ('specialite', models.ManyToManyField(to='services.specialites')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
